### DISCUSSION TITLE
Scaling WasmEdge containers in kubernetes

### DISCUSSION THREAD

**Discussion by dm4** [WasmEdge/WasmEdge#2390] [Ideas]
This demo will show how to scale up/down WasmEdge pods.

## Install kubernetes and containerd

Please follow [our document](https://wasmedge.org/book/en/use_cases/kubernetes/kubernetes/kubernetes-containerd.html) to setup `kubernetes` with `containerd` as container runtime and use `crun` as the default runtime in `containerd`.

## Check installation

Use the following commands to check if your `containerd` and `kubernetes` are ready:

```
# Check containerd
sudo ctr image pull docker.io/wasmedge/example-wasi:latest
sudo ctr run --rm \
  --runc-binary crun \
  --runtime io.containerd.runc.v2 \
  --label module.wasm.image/variant=compat-smart \
  docker.io/wasmedge/example-wasi:latest wasm-demo \
  /wasi_example_main.wasm 50000000

# Check kubernetes
sudo ./cluster/kubectl.sh run -i --restart=Never wasi-demo \
    --image=docker.io/wasmedge/example-wasi:latest \
    --annotations="module.wasm.image/variant=compat-smart" \
    --overrides='{"kind":"Pod", "apiVersion":"v1", "spec": {"hostNetwork": true}}' /wasi_example_main.wasm 50000000
sudo ./cluster/kubectl.sh delete pod wasi-demo
```

## Prepare kubernetes configuration files

We will use the [wasmedge/example-wasi-http](https://hub.docker.com/r/wasmedge/example-wasi-http) image here.
Create a configuration file named `demo.yaml`. In this configuration, we will start 2 `wasmedge/example-wasi-http` pods and a load balancer:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
      - name: demo-container
        image: wasmedge/example-wasi-http:latest
        ports:
        - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 1234
```

## Apply configuration to start deployment

Start deployment and service:

```
sudo ./cluster/kubectl.sh apply -f demo.yaml

deployment.apps/demo-deployment created
service/demo-service created
```

Check status:

```
sudo ./cluster/kubectl.sh get all

NAME                                   READY   STATUS    RESTARTS   AGE
pod/demo-deployment-7cf9f9b5dd-ghmc7   1/1     Running   0          8s
pod/demo-deployment-7cf9f9b5dd-wcngx   1/1     Running   0          8s

NAME                   TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
service/demo-service   LoadBalancer   10.0.0.34    <pending>     8080:30358/TCP   8s
service/kubernetes     ClusterIP      10.0.0.1     <none>        443/TCP          3d22h

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-deployment   2/2     2            2           8s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/demo-deployment-7cf9f9b5dd   2         2         2       8s
```

Check the service:

```
sudo ./cluster/kubectl.sh port-forward service/demo-service 8080

Forwarding from 127.0.0.1:8080 -> 1234
Forwarding from [::1]:8080 -> 1234
```

```
curl -d name=WasmEdge localhost:8080

echo: name=WasmEdge
```

## Edit configuration to scale up

Edit the `demo.yaml` file, change `spec.replicas` to `5`:

```
...
metadata:
  name: demo-deployment
spec:
  replicas: 5
...
```

Apply the change:

```
sudo ./cluster/kubectl.sh apply -f demo.yaml

deployment.apps/demo-deployment configured
service/demo-service unchanged
```

Check status:

```
sudo ./cluster/kubectl.sh get all

NAME                                   READY   STATUS             RESTARTS        AGE
pod/demo-deployment-7cf9f9b5dd-6b7g7   1/1     Running            0               19s
pod/demo-deployment-7cf9f9b5dd-8s8n7   1/1     Running            0               19s
pod/demo-deployment-7cf9f9b5dd-ghmc7   1/1     Running            0               12m
pod/demo-deployment-7cf9f9b5dd-jr2f7   1/1     Running            0               19s
pod/demo-deployment-7cf9f9b5dd-wcngx   1/1     Running            0               12m

NAME                   TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
service/demo-service   LoadBalancer   10.0.0.34    <pending>     8080:30358/TCP   12m
service/kubernetes     ClusterIP      10.0.0.1     <none>        443/TCP          3d22h

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-deployment   4/5     5            4           12m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/demo-deployment-7cf9f9b5dd   5         5         4       12m
```

Check the service, again:

```
sudo ./cluster/kubectl.sh port-forward service/demo-service 8080

Forwarding from 127.0.0.1:8080 -> 1234
Forwarding from [::1]:8080 -> 1234
```

```
curl -d name=WasmEdge localhost:8080

echo: name=WasmEdge
```

---

The following steps will show how to scale up/down WasmEdge pods with kwasm-operater.

## Create a cluster

Here we use `kind` to create a fresh cluster:

```
kind create cluster
```

## Setup the kwasm operater

- [Install helm](https://helm.sh/docs/intro/install/)
- Setup the kwasm operator
	- Install the kwasm helm repository
	- Install kwasm operator
	- provision nodes

```
helm repo add kwasm http://kwasm.sh/kwasm-operator/
helm install -n kwasm --create-namespace kwasm-operator kwasm/kwasm-operator
kubectl annotate node --all kwasm.sh/kwasm-node=true
```

Check cluster status:

```
kubectl get all

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   32s
```

## Prepare kubernetes configuration files

We will use the [wasmedge/example-wasi-http](https://hub.docker.com/r/wasmedge/example-wasi-http) image here.
Create a configuration file named `demo.yaml`. In this configuration, we will start 2 `wasmedge/example-wasi-http` pods and a load balancer:

```yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: crun
handler: crun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
      - name: demo-container
        image: wasmedge/example-wasi-http:latest
        ports:
        - containerPort: 1234
      runtimeClassName: crun
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 1234
```

## Apply configuration to start deployment

Start deployment and service:

```
kubectl apply -f demo.yaml

runtimeclass.node.k8s.io/crun created
deployment.apps/demo-deployment created
service/demo-service created
```

Check cluster status:

```
kubectl get all

NAME                                   READY   STATUS    RESTARTS   AGE
pod/demo-deployment-65d47875d4-8m5db   1/1     Running   0          9s
pod/demo-deployment-65d47875d4-nqn8x   1/1     Running   0          9s

NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/demo-service   LoadBalancer   10.96.210.184   <pending>     8080:30716/TCP   9s
service/kubernetes     ClusterIP      10.96.0.1       <none>        443/TCP          57s

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-deployment   2/2     2            2           9s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/demo-deployment-65d47875d4   2         2         2       9s
```

Check the service:

```
kubectl port-forward service/demo-service 8080

Forwarding from 127.0.0.1:8080 -> 1234
Forwarding from [::1]:8080 -> 1234
```

```
curl -d name=WasmEdge localhost:8080

echo: name=WasmEdge
```

## Edit configuration to scale up

Edit the `demo.yaml` file, change `spec.replicas` to `5`:

```
...
metadata:
  name: demo-deployment
spec:
  replicas: 5
...
```

Apply the change:

```
kubectl apply -f demo.yaml

runtimeclass.node.k8s.io/crun unchanged
deployment.apps/demo-deployment configured
service/demo-service unchanged
```

Check cluster status:

```
kubectl get all

NAME                                   READY   STATUS    RESTARTS   AGE
pod/demo-deployment-65d47875d4-8m5db   1/1     Running   0          56s
pod/demo-deployment-65d47875d4-gpps2   1/1     Running   0          10s
pod/demo-deployment-65d47875d4-h9cpg   1/1     Running   0          10s
pod/demo-deployment-65d47875d4-nqn8x   1/1     Running   0          56s
pod/demo-deployment-65d47875d4-zthcb   1/1     Running   0          10s

NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/demo-service   LoadBalancer   10.96.210.184   <pending>     8080:30716/TCP   56s
service/kubernetes     ClusterIP      10.96.0.1       <none>        443/TCP          104s

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-deployment   5/5     5            5           56s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/demo-deployment-65d47875d4   5         5         5       57s
```

Check the service, again:

```
kubectl port-forward service/demo-service 8080

Forwarding from 127.0.0.1:8080 -> 1234
Forwarding from [::1]:8080 -> 1234
```

```
curl -d name=WasmEdge localhost:8080

echo: name=WasmEdge
```
