### DISCUSSION TITLE
Autoscaling WasmEdge containers in kubernetes

### DISCUSSION THREAD

**Discussion by dm4** [WasmEdge/WasmEdge#2408] [Ideas]
This demo will show how to autoscale WasmEdge pods with [KWasm] and [KEDA].

## Requirement

- A kubernetes cluster. Here we use [kind] to start a cluster.
- [Install helm](https://helm.sh/docs/intro/install/)

## Create a cluster

Here we use `kind` to create a fresh cluster:

```
kind create cluster
```

## Setup KWasm

```
helm repo add kwasm http://kwasm.sh/kwasm-operator/
helm repo update
helm install -n kwasm --create-namespace kwasm kwasm/kwasm-operator
kubectl annotate node --all kwasm.sh/kwasm-node=true
```

## Setup KEDA

```
helm repo add kedacore https://kedacore.github.io/charts
helm repo update
helm install -n keda --create-namespace keda kedacore/keda
helm install -n keda --create-namespace http-add-on kedacore/keda-add-ons-http
```

## Prepare kubernetes configuration files

We will use the [wasmedge/example-wasi-http](https://hub.docker.com/r/wasmedge/example-wasi-http) image here. Create a configuration file named `demo.yaml`:

```yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: crun
handler: crun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
      - name: demo-container
        image: wasmedge/example-wasi-http:latest
        ports:
        - containerPort: 1234
      runtimeClassName: crun
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 1234
---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: demo-scale
spec:
  host: localhost:8080
  targetPendingRequests: 100
  scaleTargetRef:
    deployment: demo-deployment
    service: demo-service
    port: 8080
  replicas:
    min: 0
    max: 10
```

In this configuration, we use `HTTPScaledObject` provieded by KEDA to monitor the metrics and increases or decreases the number of replicas as needed.

## Cluster status

```
kubectl get all

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   13m
```

## Apply configuration

```
kubectl apply -f demo.yaml

runtimeclass.node.k8s.io/crun created
deployment.apps/demo-deployment created
service/demo-service created
httpscaledobject.http.keda.sh/demo-scale created
```

Check the cluster status:

```
kubectl get all

NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/demo-service   LoadBalancer   10.96.123.144   <pending>     8080:31869/TCP   51s
service/kubernetes     ClusterIP      10.96.0.1       <none>        443/TCP          14m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-deployment   0/0     0            0           51s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/demo-deployment-65d47875d4   0         0         0       51s

NAME                                                          REFERENCE                    TARGETS               MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/keda-hpa-demo-scale-app   Deployment/demo-deployment   <unknown>/100 (avg)   1         10        0          51s
```

Because we specify the minimum number of replicas to 0, there is no WasmEdge pods since there is no traffic.

## Autoscale with traffic

Use `port-forward` to expose keda http interceptor proxy:

```
kubectl port-forward -n keda service/keda-add-ons-http-interceptor-proxy 8080

Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
```

Send the http request and check the cluster status:

```
curl -d name=WasmEdge localhost:8080

echo: name=WasmEdge
```

```
kubectl get all

NAME                                   READY   STATUS    RESTARTS   AGE
pod/demo-deployment-65d47875d4-qkwpx   1/1     Running   0          21s

NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/demo-service   LoadBalancer   10.96.123.144   <pending>     8080:31869/TCP   3m19s
service/kubernetes     ClusterIP      10.96.0.1       <none>        443/TCP          16m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-deployment   1/1     1            1           3m19s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/demo-deployment-65d47875d4   1         1         1       3m19s

NAME                                                          REFERENCE                    TARGETS       MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/keda-hpa-demo-scale-app   Deployment/demo-deployment   0/100 (avg)   1         10        1          3m19s
```

The first response may experience a slight delay as it takes time to create the initial WasmEdge pod to handle the traffic. Following the request, we can confirm that a WasmEdge pod has been created.

If there is no traffic for an extended period, the KEDA scaler will automatically scale down the deployment to zero.

```
kubectl get all


NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/demo-service   LoadBalancer   10.96.123.144   <pending>     8080:31869/TCP   9m14s
service/kubernetes     ClusterIP      10.96.0.1       <none>        443/TCP          22m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/demo-deployment   0/0     0            0           9m14s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/demo-deployment-65d47875d4   0         0         0       9m14s

NAME                                                          REFERENCE                    TARGETS               MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/keda-hpa-demo-scale-app   Deployment/demo-deployment   <unknown>/100 (avg)   1         10        0          9m14s
```

[KWasm]: https://kwasm.sh
[KEDA]: https://keda.sh
[kind]: https://kind.sigs.k8s.io
