### ISSUE TITLE
No IP address assigned for pods when "hostNetwork: false" in k8s

### ISSUE THREAD

**Issue by GreyBalloonYU** [WasmEdge/WasmEdge#1692]
## Description
When I follow the instruction (https://wasmedge.org/book/en/kubernetes/kubernetes/kubernetes-crio.html#a-webassembly-based-http-service) to make a WebAssembly-based HTTP service, I try to assign "false" to "hostnetwork" in yaml, as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: http-server
  namespace: default
  annotations:
    module.wasm.image/variant: compat
spec:
  hostNetwork: false  #default value
  containers:
  - name: http-server
    image: avengermojo/http_server:with-wasm-annotation
    command: [ "/http_server.wasm" ]
    ports:
    - containerPort: 1234
      protocol: TCP
    livenessProbe:
      tcpSocket:
        port: 1234
      initialDelaySeconds: 3
      periodSeconds: 30
```
But the result is: these is no IP address assigned for the pod:
```
NAME          READY   STATUS    RESTARTS   AGE   IP       NODE        NOMINATED NODE   READINESS GATES
http-server   1/1     Running   0          9s    <none>   127.0.0.1   <none>           <none>
```
Does the pod have IP address only when "hostNetwork: true"? 
Are there any solutions to solve this problem?
Or cannot solve it because the inherent characteristics of WebAssembly?
## Environment

- Hardware Architecture: x86_64
- Operating system:  Ubuntu 20.04

**Comment by hydai** [comment]
Hi @GreyBalloonYU 

AFAIK, the IP means the public IP, if you set the hostnetwork to false, then it should not have the IP. I am not so familiar with k8s, if I said something wrong, please correct me, thanks.

**Comment by GreyBalloonYU** [comment]
@hydai The IP is a virtual IP of the k8s pod. When I deploy a container like busybox in k8s, which "hostnetwork" is "false", k8s will assign a virtual IP for pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  hostNetwork: false
  containers:
  - name: busybox
    image: library/busybox
    command: [ "sleep", "3600" ]
```
Then the pod will have a virtual IP address:
```
NAME      READY   STATUS    RESTARTS   AGE    IP           NODE        NOMINATED NODE   READINESS GATES
busybox   1/1     Running   0          8m4s   10.85.6.83   127.0.0.1   <none>           <none>
```
But a wasm app isn't assigned a virtual IP, which may make wasmedge difficult to be popularized in k8s.
