### ISSUE TITLE
Can not connect k8s service when using xxx.yyy.svc.cluster.local in container.

### ISSUE THREAD

**Issue by TaurusM** [WasmEdge/WasmEdge#1987]
code:
![image](https://user-images.githubusercontent.com/28164162/196462504-c90a67bc-e256-4868-ac5f-befc9bfcc7db.png)

rust dependencies:
![image](https://user-images.githubusercontent.com/28164162/196463050-1cbf2d7b-a32e-461d-ab78-cdff906852ad.png)

built by Dockerfile:
![image](https://user-images.githubusercontent.com/28164162/196462739-b30e7f29-ea99-4d15-b279-00821546f81a.png)

build commands:
```shell
rustup target add wasm32-wasi
cargo build --target wasm32-wasi --package panilake-user --release 
buildah build --annotation "module.wasm.image/variant=compat-smart" -t panilake-user .
buildah --tls-verify=false push panilake-user docker://192.168.21.213:5000/panilake-functions/panilake-user:10.18.20
```

curl result:
![image](https://user-images.githubusercontent.com/28164162/196463672-26bf09b7-7a11-49d3-bddc-824d431e9aa0.png)

So, what is the problem? or it's only support on the k8s node and can not run properly in k8s container, please help.

**Comment by 0xE282B0** [comment]
Hi,
Great that you want to use WasmEdge in Kubernetes!

In your `curl` you get a response from an envoy and it is submitted from outside the cluster to `panilake-dev.com`. I guess, it it goes through the ingress to a service and hits a pod with the wasm-slim container with code from picture-1. That container tries to resolve the service `id-wasm.panilake-dev.svc.cluster.local` and fails. 
Am I right? What is running at the service `id-wasm.panilake-dev.svc.cluster.local`?

Could you describe your setup a bit more or add a link to your repo?
The K8s Manifests for the deployment and service would be helpful too. 😊

**Comment by 0xE282B0** [comment]
@hydai When I use the hyper client example and a native wasm-image I get almost the same error:
```
GET and get result as string: http://wasm-echo-service.default.svc.cluster.local
Error: hyper::Error(Connect, ConnectError("dns error", Os { code: 85, kind: Uncategorized, message: "Success" }))
```
As Server I use `wasmedge/example-wasi-http:latest` and with a curl container `wasm-echo-service.default.svc.cluster.local` can be resolved.

---

Code:
```rust
#![deny(warnings)]
#![warn(rust_2018_idioms)]
use hyper::{body::HttpBody as _, Client};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<()> {
    pretty_env_logger::init();

    let url_str = "http://wasm-echo-service.default.svc.cluster.local";
    println!("\nGET and get result as string: {}", url_str);
    let url = url_str.parse::<hyper::Uri>().unwrap();
    fetch_url_return_str(url).await
}

async fn fetch_url_return_str (url: hyper::Uri) -> Result<()> {
    let client = Client::new();
    let mut res = client.get(url).await?;

    let mut resp_data = Vec::new();
    while let Some(next) = res.data().await {
        let chunk = next?;
        resp_data.extend_from_slice(&chunk);
    }
    println!("{}", String::from_utf8_lossy(&resp_data));

    Ok(())
}
```
Dockerfile:

```Dockerfile
FROM --platform=$BUILDPLATFORM rust:1.64 AS buildbase
RUN rustup target add wasm32-wasi
WORKDIR /src

FROM --platform=$BUILDPLATFORM buildbase AS buildclient
COPY client/ /src
RUN --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/cache \
    --mount=type=cache,target=/usr/local/cargo/registry/index \
    cargo build --target wasm32-wasi --release

FROM scratch AS client
ENTRYPOINT [ "/wasmedge_hyper_client.wasm" ]
COPY --from=buildclient /src/target/wasm32-wasi/release/wasmedge_hyper_client.wasm  wasmedge_hyper_client.wasm
```
Job.yaml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: wasmedge-hyper-client
spec:
  template:
    metadata:
      creationTimestamp: null
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
      - image: 0xe282b0/wasmedge-hyper-client
        name: wasmedge-hyper-client
        resources: {}
      restartPolicy: Never
      runtimeClassName: crun
status: {}
```
