### ISSUE TITLE
 Exec format error on exec container process on arm64 linux

### ISSUE THREAD

**Issue by Patrick0308** [WasmEdge/WasmEdge#2238]
## Description
Test it on Ubuntu 22.04.1 TLS  arm64.
wasm download from here: https://github.com/second-state/wasm-learning/blob/master/cli/wasi/wasi_example_main.wasm.
Dockerfile is
```yaml
FROM scratch
ADD wasi_example_main.wasm /
CMD ["/wasi_example_main.wasm"]
```
Command is 
```bash
$ sudo buildah build --annotation "module.wasm.image/variant=compat-smart" -t wasm-wasi-example .
$ sudo buildah push wasm-wasi-example docker://docker.io/patrick0308/example-wasi:latest
$ sudo buildah from localhost/wasm-wasi-example:latest
wasm-wasi-example-working-container
$ sudo buildah run wasm-wasi-example-working-container /wasi_example_main.wasm 50000000
2023-01-29T03:32:51.000548675Z: exec container process `/wasi_example_main.wasm`: Exec format error
```
Ctr command:
```bash
sudo ctr run --rm --runc-binary crun --runtime io.containerd.runc.v2 --label module.wasm.image/variant=compat-smart docker.io/patrick0308/example-wasi:latest wasm-example /wasi_example_main.wasm 50000000
{"msg":"exec container process `/wasi_example_main.wasm`: Exec format error","level":"error","time":"2023-01-29T06:40:53.000056416Z"}
```
## Environment

```
$ crun --version
crun version 0.17
commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
```
```
$ ctr --version
ctr containerd.io 1.6.15
```

**Comment by juntao** [comment]
The problem here is that `buildah run` does not know how to run a Wasm container. It is expecting a Linux container. 

I recommend using Docker to build, publish and run:

https://github.com/juntao/book/blob/main/docs/build-and-run/docker_wasm.md

Or, in the Red Hat / OpenShift ecosystem, use Podman to do the same

https://github.com/juntao/book/blob/main/docs/getting-started/quick_start_redhat.md

**Comment by Patrick0308** [comment]
@juntao I test with configured containerd which has crun plugin. It was same error.
Containerd config file is
```toml
version = 2
[plugins."io.containerd.grpc.v1.cri".containerd]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
    # crun: https://github.com/containers/crun
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.crun]
      runtime_type = "io.containerd.runc.v2"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.crun.options]
        BinaryName = "/usr/bin/crun"
```
Result is
```bash
$ sudo ctr run --rm --runc-binary crun --runtime io.containerd.runc.v2 --label module.wasm.image/variant=compat-smart docker.io/patrick0308/example-wasi:latest wasm-example /wasi_example_main.wasm 50000000
{"msg":"exec container process `/wasi_example_main.wasm`: Exec format error","level":"error","time":"2023-01-29T06:40:53.000056416Z"}
```
