### ISSUE TITLE
bug: error trying to connect: dns error: Success (os error 85) when running on cluster

### ISSUE THREAD

**Issue by KaiWalter** [WasmEdge/WasmEdge#3317]
### Summary

When trying to call an (AKS cluster) internal service or an external service like

```
    let url =
        url::Url::parse("http://eu.httpbin.org/ip").map_err(|e| ServiceError::ParseError(e))?;
    tracing::info!("test url {}", url);

    let response = reqwest::Client::new()
        .get(url)
        .send()
        .await
        .map_err(|e| ServiceError::ReqwestError(e))?
        .text()
        .await
        .map_err(|e| ServiceError::ReqwestError(e))?;
```

I get this error when running on a cluster - with local `wasmedge run` the call is succeeding.

```
error sending request for url (http://eu.httpbin.org/ip): error trying to connect: dns error: Success (os error 85)
```

### Current State

I install [#wasmedge](https://cloud-native.slack.com/archives/C0215BBK248) 0.3.0 with [#kwasm](https://cloud-native.slack.com/archives/C05P2KNK7RV) node installer [ghcr.io/kwasm/kwasm-node-installer:v0.3.1](http://ghcr.io/kwasm/kwasm-node-installer:v0.3.1) on AKS,

add a runtime class,

```
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmedge-v1
handler: wasmedge
scheduling:
  nodeSelector:
    agentpool: wasm
```

deploy a service with [#knative-serving](https://cloud-native.slack.com/archives/C04LMU0AX60),

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: distributor
  namespace: default
spec:
  template:
    spec:
      runtimeClassName: wasmedge-v1
      timeoutSeconds: 1
      containers:
        - name: http-server
          image: { will be replaced by deployment script }
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
  traffic:
    - latestRevision: true
      percent: 100
```

### Expected State

I expect DNS resolution of cluster is applied and call to internal and external services is succeeding.

### Reproduction steps

1. Build with options : `wasmedge compile target/wasm32-wasi/release/warpwasi_dapr_rs.wasm target/warpwasi_dapr_rs.wasm`
2. Execute with flags : see [call to WasmEdge SDK in runwasi containerd shim](https://github.com/containerd/runwasi/tree/main/crates/containerd-shim-wasmedge)
3. Execute with inputs : n.a.
4. Get error

----

infrastructure: <https://github.com/ZEISS/enterprise-wasm/tree/knative/infra/aks-kn-dapr>
module: <https://github.com/ZEISS/enterprise-wasm/tree/knative/samples/warpwasi-dapr-rs>

### Components

Rust SDK

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

CBL-Mariner/Linux

### Hardware Architecture

arm64

**Comment by leothetryhard** [comment]
For anyone facing the same issue, the workaround is providing the IP to the cluster DNS via environment variable in the deployment yaml:
```yaml
containers:
  - name: http-server
    ...
    env:
       - name: DNS_SERVER
         value: "<ClusterIP>:53"
```
Get the IP with `kubectl get svc -n kube-system kube-dns`
